spring.main.lazy-initialization=true

management.endpoints.web.exposure.include=info,health,beans,loggers,mappings,metrics
management.endpoint.health.show-details=always

spring.jpa.properties.hibernate.generate_statistics=true
spring.jpa.properties.hibernate.log_slow_query=1000

springdoc.swagger-ui.enabled=true

bootui.enabled=on
bootui.mcp.enabled=on
