spring.application.name=spring-blog-api
server.port=8080
spring.docker.compose.lifecycle-management=start_and_stop

spring.mvc.apiversion.default=1.0
spring.mvc.apiversion.use.header=API_VERSION
spring.mvc.apiversion.supported=1.0

server.compression.enabled=true
server.http2.enabled=true
spring.threads.virtual.enabled=true

###### App ######
blog.email-service-type=console
blog.support-email=siva@gmail.com
blog.page-size=5
blog.newsletter-job-cron=0 0 9 * * 6
blog.cors.path-pattern=/api/**
blog.cors.allowed-origins=*
blog.cors.allowed-methods=*
blog.cors.allowed-headers=*

blog.openapi.title=Blog API
blog.openapi.description=Blog API Swagger Documentation
blog.openapi.version=v1.0.0
blog.openapi.contact.name=SivaLabs
blog.openapi.contact.email=support@sivalabs.in

blog.jwt.issuer=SivaLabs
blog.jwt.expires-in-seconds=604800
blog.jwt.private-key=classpath:certs/private.pem
blog.jwt.public-key=classpath:certs/public.pem

###### Logging ######
logging.level.root=INFO
logging.level.com.sivalabs=DEBUG
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}] 
logging.include-application-name=false
#logging.level.org.springframework.security=DEBUG

###### BootUI ######
bootui.enabled=off
bootui.mcp.enabled=off

###### Springdoc ######
springdoc.swagger-ui.enabled=false
springdoc.paths-to-match=/api/**

###### Database ######
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.datasource.hikari.auto-commit=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.jdbc.batch_size=15
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true

###### JavaMail ######
spring.mail.host=${EMAIL_HOST:127.0.0.1}
spring.mail.port=1025
spring.mail.protocol=smtp
spring.mail.username=siva@sivalabs.com
spring.mail.password=secret
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtps.auth=true
spring.mail.properties.mail.smtps.starttls.enable=true
spring.mail.properties.mail.smtps.timeout=2000

###### Actuator ######
#management.endpoints.web.exposure.include=info,health,metrics
#management.endpoint.health.show-details=when_authorized
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

###### Spring Modulith ######
spring.modulith.events.jdbc.schema-initialization.enabled=true
spring.modulith.events.completion-mode=update
spring.modulith.events.republish-outstanding-events-on-restart=true

###### axelix ######
axelix.sbs.auth.jwt.algorithm=HMAC256
axelix.sbs.auth.jwt.signing-key=8DrZJSOJ8vkbxdjUB3sSsyeiG4Xidf1sDNmJq1Slkkn
axelix.sbs.discovery.self-registration=true
axelix.sbs.discovery.instance-name=spring-blog-api
axelix.sbs.discovery.instance-actuator-url=http://localhost:8080/actuator
axelix.sbs.discovery.master-url=http://localhost:9444/api/internal/service/register
