name: "spring-blog-api"
services:
  spring-blog-api:
    image: sivaprasadreddy/spring-blog-api
    environment:
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://blog-db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      EMAIL_HOST: mailpit
    ports:
      - "8080:8080"
      - "5005:5005"
    restart: unless-stopped
    depends_on:
      - blog-db
      - mailpit

  blog-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  mailpit:
    image: axllent/mailpit:v1.29
    ports:
      - "1025:1025"
      - "8025:8025"
